version: "3.9"
services:

  db:
    image: postgres:16
    container_name: booksight-db-compose
    restart: unless-stopped
    environment:
      POSTGRES_DB: booksight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - booksight_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nlp-service:
    build:
      context: ../NLP-Service
    container_name: booksight-nlp-service
    restart: unless-stopped
    ports:
      - "8000:8000"

  backend:
    build:
      context: .
    container_name: booksight-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      db:
        condition: service_healthy
      nlp-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/booksight
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      NLP_SERVICE_URL: http://nlp-service:8000
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      SENTRY_DSN: https://f39fa438439d579aa40c846e3519bda4@o4511597780860928.ingest.de.sentry.io/4511597786300496

volumes:
  booksight_pgdata:
