spring.application.name=booksight
server.port=8080
server.address=0.0.0.0

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/booksight
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway

spring.flyway.enabled=true
google.books.api.key=${GOOGLE_BOOKS_API_KEY}
google.books.api.url=https://www.googleapis.com/books/v1

# NLP Service
nlp.service.url=http://172.20.16.1:8000